Primitives-xyz/explorer

- src/app/api/followers/follow-wallet/route.ts
- src/app/api/profiles/create/route.ts
- need to ensure all profiles have images
> Add Image to profile create

- next.config.mjs
- src/components/ProfileSection.tsx
- src/components/common/Avatar.tsx
Profile content should use Avatar
Improve Next.Config for external urls
> external images in next config

- src/app/[id]/page.tsx
- src/utils/metadata/profile-metadata.ts
- src/utils/profile.ts
> OG image v2

- src/app/api/content/[id]/route.ts
- src/app/api/content/batch/route.ts
- src/app/api/content/route.ts
- src/lib/content-server.ts
Going to use this for copy trade
> add routes and service for content nodes

- src/app/api/profiles/route.ts
Added namespace info into identities.
> TAP-553 - add namespace info

- src/components/ProfileSection.tsx
- src/components/profile/ProfileInfo.tsx
> ProfileInfo Card format

- package.json
- src/app/api/tokens/[mint]/holders/route.ts
- src/components/FungibleTokenDetails.tsx
- src/components/social/people-in-common/PeopleInCommonSection.tsx
- src/components/tokens/FungibleTokenDetailsWrapper.tsx
- src/components/tokens/token-view.tsx
- src/hooks/use-people-in-common.ts
https://linear.app/tap/issue/TAP-582/[explorer]-add-component-to-token-view
Seems to be working now :)
This PR intregrates the token owners view into the token view for the Explorer.
> TAP-582 - [Explorer] - Add component to token view

- src/components/social/people-in-common/PeopleInCommonSection.tsx
Should look like this now ^
Also links are now clickable
> TAP-582 - Cleans up UI to look more like the site should

- src/components/tokens/token-information.tsx
https://x.com/0xNFTsHunter/status/1889935183291490396
> make CA more prominent on token detail page

- src/components/profile/update-profile-modal.tsx
> Choose File white text

- pnpm-lock.yaml
- src/lib/tapestry.ts
Create Notification types `IBaseNotification`, `ITransactionCopiedNotification`, `IEarningsNotification`
Create notification types for `EARNINGS_RECEIVED`
> Notification when SSE Trade Earnings sent TAP-630

- src/components/profile-section.tsx
> Remove nimbus link

- src/components/fungible-token-details.tsx
- src/components/transactions/swap/swap-form.tsx
> Remove default swap amount

- pnpm-lock.yaml
- src/app/api/llm/route.ts
- src/components/transactions/transaction-view.tsx
- src/hooks/useTransactionExplanation.ts
> Improve AI transaction explanation

- src/app/api/namespace/[name]/route.ts
- src/app/api/profiles/route.ts
- src/app/namespace/[namespace]/page.tsx
- src/components/common/data-container.tsx
- src/components/profile-section.tsx
- src/hooks/use-get-namespace-details.ts
- src/hooks/use-get-namespace-profiles.ts
- src/lib/content-server.ts
Clicking namespace icon, goes to Namespace page
Namespace page lists recent profiles and links to profile url on their namespace
http://localhost:3000/namespace/primitives
internal explorer profiles don't go to this page
> Namespace Page TAP-670

- src/app/api/og/namespace/route.tsx
- src/app/namespace/[namespace]/namespace-client.tsx
- src/app/namespace/[namespace]/page.tsx
- src/utils/metadata/namespace-metadata.ts
- src/utils/namespace.ts
- src/utils/validation.ts
OG Image on Namespace profiles
> Namespace page OG

- src/components/notifications/dialect-notifications-component.tsx
Changes need to get notifications connected
> configure dialect to use dynamic as a wallet connector

- src/app/namespace/[namespace]/namespace-client.tsx
- src/hooks/use-get-namespace-details.ts
> Namespace Profiles have wallets TAP-696

- src/app/(legacy)/legacy.css
- src/components/header-container/user-actions.tsx
- src/components/notifications/dialect-notifications-component.tsx
css should probably be improved
> get dialect bell working on explorer

- package.json
- pnpm-lock.yaml
- src/app/(legacy)/trade/page.tsx
- src/app/actions.json/route.ts
- src/app/api/actions/trade/route.ts
- src/utils/helius/das-api.ts
Getting the 101s of blinks by setting up the trade page
> Set up Solana Blinks for explorer

- src/app/(legacy)/layout.tsx
- src/app/(new-version)/layout.tsx
- src/app/layout.tsx
- src/components-new-version/common/wallet-provider.tsx
new wallet provider for new version, which removes all the un-necessary re-renders of the page
> new wallet provider

- src/components-new-version/swap/components/swap-tray.tsx
fix swap tray for small screens
> fix swap tray for small screens

- src/components-new-version/onboarding/components/onboarding.tsx
- src/components-new-version/onboarding/components/suggested-follow.tsx
- src/components-new-version/ui/popover/dropdown-menu.tsx
https://linear.app/tap/issue/TAP-942/onboarding-modal-pops-up-for-profile-that-has-already-onboarded
> fix onboarding TAP-942

- src/components/swap/components/swap.tsx
- src/components/trade/hooks/use-jupiter-swap.ts
> fix reverse swap token pair issue

- src/components/swap/components/swap.tsx
> fix copy trading

- next.config.mjs
- node-browser-compatibility/index.js
- package.json
- pnpm-lock.yaml
- src/components/common/left-side-menu/left-side-menu.tsx
- src/components/trade/hooks/drift/use-deposit.ts
- src/components/trade/hooks/drift/use-initialize-drift.ts
- src/components/trade/left-content/perpetual/add-funds-modal.tsx
- src/components/trade/left-content/perpetual/perpetual.tsx
> feat: Market UI

- src/components/trade/hooks/drift/use-place-perps-order.ts
- src/components/trade/left-content/perpetual/perpetual.tsx
> feat: place perps order

- src/components/trade/hooks/drift/use-deposit.ts
> fix: new wallet deposite

- src/components/trade/hooks/drift/use-deposit.ts
- src/components/trade/hooks/drift/use-drift-users.ts
- src/components/trade/hooks/drift/use-place-perps-order.ts
- src/components/trade/left-content/perpetual/add-funds-modal.tsx
- src/components/trade/left-content/perpetual/perpetual.tsx
> add hooks for drifts users

- package.json
- pnpm-lock.yaml
- src/components/tapestry/models/drift.model.ts
- src/components/trade/hooks/drift/use-place-perps-order.ts
- src/components/trade/hooks/drift/use-user-stats.ts
- src/components/trade/left-content/perpetual/leverage-selector.tsx
- src/components/trade/left-content/perpetual/limit-order.tsx
- src/components/trade/left-content/perpetual/market-order.tsx
- src/components/trade/left-content/perpetual/perpetual.tsx
- src/components/ui/slider/slider.tsx
> add oracleofferset in perps order

- src/components/trade/hooks/use-create-trade-content.ts
- src/components/trade/hooks/use-jupiter-swap.ts
Reimplement logic takin out during refactor
> TAP-991 Create content node after successful trade to track for trade copy payouts

- src/components/trade/hooks/drift/use-leverage-size.ts
- src/components/trade/hooks/drift/use-user-stats.ts
- src/components/trade/left-content/perpetual/leverage-selector.tsx
- src/components/trade/left-content/perpetual/limit-order.tsx
- src/components/trade/left-content/perpetual/market-order.tsx
- src/components/trade/left-content/perpetual/perpetual.tsx
> fix: maxleverage and maxtradesize

- src/components/trade/hooks/use-token-balance.ts
> update: use-token-balance hook

- src/components/trade/left-content/perpetual/perpetual.tsx
> fix: order amount

- src/components/trade/left-content/perpetual/perpetual.tsx
> fix: orderAmount

- src/components/trade/hooks/drift/use-deposit.ts
- src/components/trade/hooks/drift/use-drift-users.ts
- src/components/trade/hooks/drift/use-place-perps-order.ts
- src/components/trade/hooks/drift/use-toast-content.ts
- src/components/trade/left-content/perpetual/add-funds-modal.tsx
- src/components/trade/left-content/perpetual/market-order.tsx
- src/components/trade/left-content/perpetual/perpetual.tsx
> add toast modal to tx status

- src/components/trade/hooks/drift/use-user-stats.ts
- src/components/trade/left-content/perpetual/add-funds-modal.tsx
- src/components/trade/left-content/perpetual/button-middle-perpetual.tsx
- src/components/trade/left-content/perpetual/hero-perpetual.tsx
- src/components/trade/left-content/perpetual/perpetual.tsx
> add: block perps ui feature when no accounts

- src/components/tapestry/models/drift.model.ts
- src/components/trade/hooks/drift/use-liquidation-price.ts
- src/components/trade/hooks/drift/use-place-perps-order.ts
- src/components/trade/hooks/drift/use-user-stats.ts
- src/components/trade/left-content/perpetual/bottom-perpetual.tsx
- src/components/trade/left-content/perpetual/hero-perpetual.tsx
- src/components/trade/left-content/perpetual/perpetual.tsx
> fix: big leverage

- src/components/swap/components/swap-elements/pay.tsx
- src/components/swap/components/swap-elements/received.tsx
- src/components/swap/components/swap.tsx
Not display sse image in swap tray input by default
> not display sse images in swap tray TAP-955

- src/app/page.tsx
- src/components/swap/components/platform-comparison.tsx
- src/components/swap/components/swap-tray.tsx
- src/components/ui/accordion/accordion.tsx
fix swap tray button and fix ui
> swap tray button TAP-1034

- src/app/[id]/page.tsx
fix profile layout with swap tray
https://linear.app/tap/issue/TAP-1037/profile-is-shrinked-to-the-left
> fix profile layout TAP-1037

- src/components/transactions/common/swap-line.tsx
- src/components/transactions/common/token-line.tsx
- src/components/transactions/common/transfer-line.tsx
- src/components/transactions/swap-transactions/swap-transactions-view.tsx
todo: fix initial price fetch for wrapped sol
> replaced jupiter price fetching with helius for transactions

- src/components/profile/components/profile-social.tsx
Profile social twitter tabs fix
> trending token TAP-1047

- src/app/api/drift/limitorders/route.ts
- src/components/common/left-side-menu/left-side-menu.tsx
- src/components/trade/hooks/drift/use-withdraw.ts
- src/components/trade/left-content/perpetual/add-funds-modal.tsx
- src/components/trade/left-content/perpetual/funds-modal/confirm.tsx
- src/components/trade/left-content/perpetual/funds-modal/deposite.tsx
- src/components/trade/left-content/perpetual/funds-modal/init-and-deposit.tsx
- src/components/trade/left-content/perpetual/funds-modal/withdraw.tsx
- src/components/trade/left-content/perpetual/slippage.tsx
> feat: update unlock perps btn into deposite when account exist

- src/components/activity-tape/activity-tape.models.ts
- src/components/activity-tape/components/activity-tape-entry.tsx
- src/components/activity-tape/components/activity-tape.tsx
- src/components/activity-tape/hooks/use-get-feed.ts
- src/components/ui/scrolling-text/scrolling-text.tsx
bring back fake activity tape transactions (top scrolling transactions)
> bring back fake activity tape transactions

- src/components/motion/stores/use-motion-store.ts
save animation toggle state in local storage
> save animation toggle state in local storage

- src/app/[id]/page.tsx
to-do: improve route determination logic
> redirect to trade page if a token address is provided

- src/components/trade/hooks/use-jupiter-swap.ts
Bring back logic lost in the refactor
> TAP-1049 Bring back use SSE as fees

- src/components/trade/hooks/drift/use-deposit.ts
- src/components/trade/hooks/drift/use-drift-users.ts
- src/components/trade/hooks/drift/use-initialize-drift.ts
- src/components/trade/hooks/drift/use-limit-orders.ts
- src/components/trade/hooks/drift/use-liquidation-price.ts
- src/components/trade/hooks/drift/use-open-positions.ts
- src/components/trade/hooks/drift/use-place-perps-order.ts
- src/components/trade/hooks/drift/use-user-stats.ts
- src/components/trade/trade-content/positions/filter-perps-positions.tsx
- src/components/trade/trade-content/positions/orders-tab-content.tsx
- src/components/trade/trade-content/positions/perps-positions.tsx
- src/components/trade/trade-content/positions/position-tab-content.tsx
- src/components/trade/trade-content/trade-content.tsx
> refactor: Perps UI for TAP-1031

- src/app/layout.tsx
- src/components/common/mobile-menu/mobile-menu.tsx
> fix mobile layout + logout button

- src/app/api/helius-transactions/route.ts
- src/app/api/home-transactions/following/route.ts
- src/app/api/home-transactions/kol/route.ts
- src/components/home-transactions/components/home-following-transactions.tsx
- src/components/home-transactions/components/home-kol-transactions.tsx
- src/components/home-transactions/components/swap-transactions-view.tsx
- src/components/home-transactions/home-transactions.models.ts
- src/components/home-transactions/hooks/use-get-home-kol-transactions.ts
- src/styles/variables.css
- src/utils/api/use-paginated-query.ts
better loading for home transactions
load more transactions but it's slower
will need some pagination but super complicated with the logic in place
> better home transactions loading and animation

- src/app/[id]/page.tsx
- src/app/globals.css
- src/app/stake/page.tsx
- src/components/common/left-side-menu/menu.tsx
- src/components/common/left-side-menu/profile-infos.tsx
- src/components/common/mobile-menu/mobile-header.tsx
- src/components/onboarding/components/add-bio-form.tsx
- src/components/onboarding/components/add-profile-image.tsx
- src/components/onboarding/components/onboarding.tsx
- src/components/onboarding/components/suggested-follow.tsx
- src/components/profile/components/profile-content.tsx
- src/components/profile/components/profile-header.tsx
- src/components/profile/components/profile-with-username.tsx
- src/components/profile/components/profile-with-wallet.tsx
- src/components/stake/stake-content.tsx
- src/components/stake/stake-data/claims-form.tsx
- src/components/stake/stake-data/display-stake-data.tsx
- src/components/stake/stake-data/stake-data.tsx
- src/components/stake/stake-data/stake-form.tsx
- src/components/stake/stake-details/bottom-details.tsx
- src/components/stake/stake-details/stake-details.tsx
- src/components/transactions/common/token-line.tsx
- src/components/transactions/other-transactions.tsx
- src/components/transactions/sol-transfer-transactions.tsx
- src/components/transactions/swap-transactions/swap-transactions-view-details.tsx
- src/components/transactions/transactions-header.tsx
Responsive
Onboarding
profile page
stake page
> C/responsive profile + onboarding + stake page TAP-1088

- src/components/trade/hooks/drift/use-limit-orders.ts
- src/components/trade/hooks/drift/use-liquidation-price.ts
- src/components/trade/hooks/drift/use-open-positions.ts
> fix vercel issue for positions and limit orders

- src/components/stake/stake-data/stake-form.tsx
> fix: sse_balance

- src/components/stake/stake-data/stake-form.tsx
> formart balance

- src/components/profile/components/profile-social.tsx
- src/components/trade/trade-content/token-details/about-tab-content.tsx
Twiter tab fix in profile page
> twitter tabs TAP-1118

- src/app/discover/page.tsx
- src/app/page.tsx
- src/components/common/left-side-menu/menu.tsx
- src/components/home-transactions/components/transactions-header.tsx
- src/components/transactions/transactions-header.tsx
Responsive home and discover page
> home discover responsive

- src/components/common/left-side-menu/menu.tsx
- src/components/discover/trending-tokens.tsx
> fix discover page

- src/app/api/drift/marketprice/route.ts
- src/components/trade/hooks/drift/use-market-price.ts
> update: market price loading

- src/app/api/drift/limitorders/route.ts
- src/app/api/drift/perpspositions/route.ts
- src/components/trade/hooks/drift/use-limit-orders.ts
- src/components/trade/hooks/drift/use-open-positions.ts
- src/components/trade/left-content/perpetual/perpetual.tsx
- src/components/trade/trade-content/positions/orders-tab-content.tsx
- src/components/trade/trade-content/positions/perps-positions.tsx
- src/components/trade/trade-content/positions/position-tab-content.tsx
> Update: TAP-1106

- src/app/api/stake/route.ts
- src/app/api/unstake/route.ts
- src/components/stake/stake-data/unstake-form.tsx
> Fix Decimal Issue For Tap-1137

- src/app/layout.tsx
> fix entry price

- src/app/api/drift/perpspositions/route.ts
- src/app/layout.tsx
> update: entry price

- src/app/api/drift/perpspositions/route.ts
> fix pnl percentage

- src/components/stream/stream-content.tsx
- src/components/stream/token-small-buy.tsx
- src/components/swap/components/mobile-swap-tray.tsx
make buys obvious
tray looks better
> even better stream view

- src/app/[id]/page.tsx
- src/app/api/actions/trade/route.ts
- src/app/api/feed/route.ts
- src/components/common/left-side-menu/menu.tsx
- src/components/common/solana-address-display.tsx
- src/components/discover/trending-tokens.tsx
- src/components/profile/components/profile-tokens.tsx
- src/components/swap/components/swap-elements/pay.tsx
- src/components/swap/components/swap-elements/received.tsx
- src/components/swap/components/swap-elements/top-swap.tsx
- src/components/swap/components/swap.tsx
- src/components/swap/hooks/use-token-search.ts
- src/components/swap/swap.constants.ts
- src/components/swap/utils/token-utils.ts
- src/components/trade/hooks/use-token-balance.ts
- src/components/trade/left-content/perpetual/limit-order.tsx
- src/components/trade/left-content/perpetual/market-order.tsx
- src/components/trade/left-content/perpetual/stop-limit.tsx
- src/components/trade/left-content/perpetual/take-profit.tsx
- src/components/transactions/transfer-transaction/transfer-transaction-view.tsx
- src/components/trenches/trenches-content.tsx
- src/components/ui/button/button.tsx
- src/components/ui/validated-image/validated-image.tsx
- src/utils/route.ts
> C/profile token redirect to trade TAP-1178

- src/utils/entity.ts
> TAP-1163 Better wallet routing 

- src/components/common/left-side-menu/solid-score/solid-score-badges.tsx
- src/components/common/left-side-menu/solid-score/solid-score-dialog.tsx
fix solid score badges size and add image in the tooltip
> little fix badges

- src/components/tapestry/models/drift.model.ts
- src/components/trade/hooks/drift/use-open-positions.ts
- src/components/trade/hooks/drift/use-place-perps-order.ts
- src/components/trade/left-content/perpetual/add-pro-orders/add-pro-orders.tsx
- src/components/trade/left-content/perpetual/add-pro-orders/add-stop-loss.tsx
- src/components/trade/left-content/perpetual/add-pro-orders/add-take-profit.tsx
- src/components/trade/trade-content/positions/orders-tab-content.tsx
- src/components/trade/trade-content/positions/position-tab-content.tsx
> add TP/SL to existing position for TAP-1115

- src/app/api/home-transactions/all/route.ts
- src/components/home-transactions/components/home-all-transactions.tsx
- src/components/home-transactions/components/home-transactions.tsx
- src/components/home-transactions/hooks/use-get-home-all-transactions.ts
- src/messages/en.json
- src/messages/zh.json
`api/home-transactions/all` which calls Tapestry Contents plus Helius
> All Transactions homepage TAP-1241

- src/components/onboarding/components/add-bio-form.tsx
- src/components/onboarding/components/add-profile-image.tsx
- src/components/onboarding/components/create-username-form.tsx
- src/components/onboarding/components/onboarding.tsx
- src/components/onboarding/components/steps-wrapper.tsx
- src/components/onboarding/components/suggested-bios.tsx
- src/components/onboarding/components/suggested-follow.tsx
- src/components/onboarding/components/suggested-usernames.tsx
- src/messages/en.json
- src/messages/zh.json
> onboarding translations

- src/app/page.tsx
- src/components/common/mobile-menu/mobile-menu.tsx
> make /trade landing page on mobile

- src/components/home-transactions/components/home-kol-transactions.tsx
- src/components/home-transactions/components/transactions-header.tsx
Transactions usernames link to profiles
> transactions linking to profiles

- src/app/api/jupiter/perps/limit/route.ts
- src/components/tapestry/models/jupiter.models.ts
- src/components/trade/hooks/jup-perps/use-limit-orders.ts
- src/components/trade/left-content/perpetual/jup-perps/jupiter-perps.tsx
> add Limit order of Jup Perps For TAP-1302

- src/components/home-transactions/components/home-all-transactions.tsx
- src/components/home-transactions/components/home-following-transactions.tsx
- src/components/home-transactions/components/home-kol-transactions.tsx
- src/components/home-transactions/components/home-transaction-entry.tsx
`HomeTransactionEntry` does not need `walletAddress` prop
> Homescreen Source Wallet

- src/app/api/jupiter/perps/orders/limit/route.ts
- src/app/api/jupiter/perps/positions/route.ts
- src/app/trade/page.tsx
- src/components/swap/components/swap.tsx
- src/components/trade/context/trade-context.tsx
- src/components/trade/hooks/jup-perps/use-open-orders.ts
- src/components/trade/hooks/jup-perps/use-positions.ts
- src/components/trade/left-content/perpetual/drift-perps/drift-perps.tsx
- src/components/trade/left-content/perpetual/jup-perps/jupiter-perps.tsx
- src/components/trade/left-content/perpetual/updated-perpetual.tsx
- src/components/trade/left-content/trade-left-content.tsx
- src/components/trade/trade-content/positions/drift/orders-tab-content.tsx
- src/components/trade/trade-content/positions/drift/perps-positions.tsx
- src/components/trade/trade-content/positions/drift/position-tab-content.tsx
- src/components/trade/trade-content/positions/jupiter/jup-orders-tab-content.tsx
- src/components/trade/trade-content/positions/jupiter/jup-perps-positions.tsx
- src/components/trade/trade-content/positions/jupiter/jup-position-tab-content.tsx
- src/components/trade/trade-content/trade-content.tsx
> add jup perps open positions and orders for TAP-1303

- src/components/swap/components/swap.tsx
> Fix error caused by undefined token mint

- src/app/api/jupiter/perps/increase/route.ts
- src/app/api/jupiter/perps/market-stats/route.ts
- src/app/api/jupiter/perps/orders/delete/route.ts
- src/components/trade/hooks/jup-perps/use-delete-order.ts
- src/components/trade/hooks/jup-perps/use-market-stats.ts
- src/components/trade/left-content/perpetual/jup-perps/jupiter-perps.tsx
- src/components/trade/trade-content/positions/jupiter/jup-orders-tab-content.tsx
> add: open order cancel feature for TAP-1357

- src/components/trade/hooks/drift/use-place-perps-order.ts
- src/components/trade/left-content/perpetual/drift-perps/drift-perps.tsx
> fix: update drift perps direction change for TAP-1360

- src/app/api/solid-score/leaderboard/route.ts
- src/components/common/left-side-menu/menu.tsx
- src/components/solid-score/components/leaderboard/data-table-leaderboard.tsx
- src/components/solid-score/components/solid-score-badges.tsx
- src/components/solid-score/hooks/use-solid-score-leaderboard.tsx
- src/components/solid-score/hooks/use-solid-score.ts
- src/components/tapestry/models/solid.score.models.ts
- src/utils/user-permissions.ts
add user avatar in leaderboard
add leaderboard menu entry
remove discover menu entry
https://linear.app/tap/issue/TAP-1359/explorer-solid-scores-leaderboard-new-tab-profile-pics
> improve solid score leaderboard + menu entry TAP-1359

- src/components/trade/hooks/jup-perps/use-decrease-position.ts
- src/components/trade/trade-content/positions/jupiter/position-close-modal.tsx
> fix: cancel open position tx confirm issue for TAP-1371

- src/components/profile/components/profile-content.tsx
- src/components/pudgy/components/background-theme.tsx
- src/utils/api/use-mutation.tsx
fix pudgy profile ui when seeing as another user
> fix pudgy profile for external users

- src/components/common/left-side-menu/menu.tsx
- src/components/profile/components/profile-header/solid-score-profile-header.tsx
- src/components/solid-score/components/leaderboard/leaderboard-content.tsx
- src/components/solid-score/components/smart-cta/solid-score-smart-cta-wrapper.tsx
- src/components/solid-score/components/solid-score.tsx
remove admin flag for solid score feature
> launch solid score

- src/app/api/jupiter/perps/tpsl/edit/route.ts
- src/components/tapestry/models/jupiter.models.ts
- src/components/trade/hooks/jup-perps/use-edit-tpsl.ts
- src/components/trade/hooks/jup-perps/use-positions.ts
- src/components/trade/left-content/perpetual/jup-perps/jupiter-perps.tsx
- src/components/trade/trade-content/positions/jupiter/edit-tpsl-modal.tsx
- src/components/trade/trade-content/positions/jupiter/jup-position-tab-content.tsx
- src/components/trade/trade-content/positions/jupiter/tpsl-modal.tsx
> add tpsl edition feature for TAP-1374

- src/components/home-transactions/components/likes-button.tsx
Modal for Likes now includes the `Follow-Button`
> Likes Modal UI improvements

- src/app/page.tsx
- src/components/common/left-side-menu/left-side-menu.tsx
- src/components/common/left-side-menu/menu.tsx
- src/components/common/mobile-menu/mobile-menu.tsx
- src/utils/constants.ts
Fix mobile menu and menu wallet address
> fix menu address and mobile menu TAP-1294

- src/components/profile/components/profile-header/profile-header.tsx
fix pudgy ui for other profiles
> fix pudgy ui for other profiles

- PERFORMANCE_OPTIMIZATION_REPORT.md
- src/app/api/content/[id]/route.ts
- src/app/api/solid-score/[id]/route.ts
- src/app/api/tokens/[mint]/holders/route.ts
- src/app/api/tokens/balance/route.ts
- src/components/common/left-side-menu/balance.tsx
- src/components/home-transactions/hooks/use-transaction-content.ts
- src/components/pudgy/hooks/use-pudgy-payment.ts
- src/components/solid-score/hooks/use-solid-score.ts
- src/components/trade/hooks/use-token-balance.ts
- src/utils/redis-dedup.ts
To address redundant network requests, a Redis-based deduplication strategy was implemented.
*   A new utility, `src/utils/redis-dedup.ts`, was created. It features a `dedupRequest` function that uses an in-memory promise cache for immediate deduplication and Redis for very short-term caching (e.g., 1 second for balances, 3 seconds for content, 30 seconds for solid scores). This prevents concurrent duplicate requests while maintaining data freshness.
*   API routes were updated to utilize this deduplication:
*   `/api/content/[id]` now uses `dedupContent`.
*   `/api/solid-score/[id]` uses `dedupSolidScore`.
*   `/api/tokens/[mint]/holders` uses `dedupTokenHolders`.
*   `/api/tokens/balance` uses `dedupBalance` for wallet mint queries.
*   HTTP `Cache-Control` headers were added to these …
> Analyze server logs for network improvements

- src/components/pudgy/hooks/use-pudgy-profile-status.ts
remove admin allowlist from pudgy display logic
> release pudgy

- src/components/onboarding/components/page/update-username-form.tsx
> del router change in userame form For TAP-1380

- src/app/onboarding/page.tsx
> update onboarding page demo for TAP-1380

- src/components/swap/components/swap-dialog/token-list-item.tsx
> add token search result console for TAP-1476

- src/app/api/dialect/apps/route.ts
- src/app/apps/page.tsx
- src/components/dialect-app/hooks/use-apps-data.ts
> Rusty/tap 1442 for TAP-1442

- src/messages/zh.json
> add zh translation file for TAP-1437

- src/components/search/components/search-button.tsx
> add search in mobile view for TAP-1091
